### ISSUE TITLE
Linker errors for String_lastIndexOf procedures

### ISSUE THREAD

**Issue by nhitz** [TypoKign/MASM3#3]
MASM3.obj : error LNK2001: unresolved external symbol _String_lastIndexOf_1
MASM3.obj : error LNK2001: unresolved external symbol _String_lastIndexOf_2
MASM3.obj : error LNK2001: unresolved external symbol _String_lastIndexOf_3
MASM3.exe : fatal error LNK1120: 3 unresolved externals

`extern String_lastIndexOf_1: Near32, String_lastIndexOf_2: Near32, String_lastIndexOf_3: Near32` doesn't fix

**Comment by typokign** [comment]
fixed -- PROCs were labeled as String_lastIndexOf1, String_lastIndexOf2, String_lastIndexOf3 in String2.asm (missing underscores between Of and number)
